### ISSUE TITLE
Disable refresh button during contest

### ISSUE THREAD

**Issue by pbhopalka** [pbhopalka/Debugger#1]
1. Disable refresh button or don't allow to be refreshed when contest is going on

**Comment by SpEcHiDe** [comment]
function disableF5(e) { if ((e.which || e.keyCode) == 116) e.preventDefault(); };

**Comment by pbhopalka** [comment]
That's a good script.. But there are several ways of refreshing a page.. We are working on a way so that even if you refresh the page, there's no benefit to the participant. Its kind of complete. Needs some testing though.

**Comment by Suraj-Yadav** [comment]
This is issue is closed now. Made a function which syncs the timer every 10 sec, so even after refresh the updated time will be used.
